src/Entity/Personne.php
<?php

namespace App\Entity;

class Personne
{

    protected $email;
    protected $nom;

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail(mixed $email): void
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    public function setNom(mixed $nom): void
    {
        $this->nom = $nom;
    }


    /**
     * @param string $value
     */
    public function setNomEmail($value): void
    {
        if (is_string($value)){
            if (!str_contains($value,':')){

            }
            else{
                [$this->nom, $this->email] = explode(':',$value);
            }
        }
        elseif(is_array($value)){
            $this->nom = $value['nom'];
            $this->email = $value['email'];

        }

    }


    public function getCle()
    {
        return strtolower(trim($this->nom).':'.trim($this->email));
    }


}

src/Entity/Tache.php
<?php

namespace App\Entity;

class Tache
{

    /**
     * @var integer
     */
    protected $id;


    /**
     * @var string
     */
    protected $uid;

    /**
     * @var string
     */
    protected $agenda;


    /**
     * @var string
     */
    protected $serveur;

    /**
     * @var string
     */
    protected $titre;
    /**
     * @var string
     */
    protected $descriptif;
    /**
     * @var \DateTime
     */
    protected $date_debut;
    /**
     * @var \DateTime
     */
    protected $date_fin;

    /**
     * @var array|null
     */
    protected $participants;
    /**
     * @var array|null
     */
    protected $organisateurs;



    /**
     * @var string
     */
    protected $priorite="";


    /**
     * @var string
     */
    protected $avancement="";

    /**
     * @var bool
     */
    protected $fini=false;

    /**
     * @var string
     */
    protected $lieu="";

    /**
     * @var string
     */
    protected $adresse="";

    /**
     * @var string
     */
    protected $groupe="";


    /**
     * @var array
     */
    protected $categories = null;


    /**
     * @var string
     */
    protected $statut="";

    /**
     * @var string
     */
    protected $couleur="";


    /**
     * @var array
     */
    protected $commentaires=[];







    /**
     * @return string
     */
    public function getUid(): string
    {
        return $this->uid;
    }

    /**
     * @param string $uid
     */
    public function setUid(string $uid): void
    {
        $this->uid = $uid;
    }

    /**
     * @return string
     */
    public function getTitre(): string
    {
        return $this->titre;
    }

    /**
     * @param string $titre
     */
    public function setTitre(string $titre): void
    {
        $this->titre = $titre;
    }






    /**
     * @return string
     */
    public function getDescriptif(): string
    {
        return $this->descriptif;
    }

    /**
     * @param string $descriptif
     */
    public function setDescriptif(string $descriptif): void
    {
        $this->descriptif = $descriptif;


    }

    /**
     * @return array
     */
    public function getCommentaires(): array
    {
        return $this->commentaires;
    }

    /**
     * @param array $commentaires
     */
    public function setCommentaires(array $commentaires): void
    {
        $this->commentaires = $commentaires;
    }






    /**
     * @return null|\DateTime
     */
    public function getDateDebut(): ?\DateTime
    {
        return $this->date_debut;
    }

    /**
     * @param \DateTime $date_debut
     */
    public function setDateDebut(\DateTime $date_debut): void
    {
        $this->date_debut = $date_debut;
    }

    /**
     * @return \DateTime
     */
    public function getDateFin(): \DateTime
    {
        return $this->date_fin;
    }

    /**
     * @param \DateTime $date_fin
     */
    public function setDateFin(\DateTime $date_fin): void
    {
        $this->date_fin = $date_fin;
    }


    /**
     * @return array|null
     */
    public function getParticipantsTab(): ?array
    {
        $temp =[];
        foreach($this->participants as $p){
            $temp[]=$p->getNom().':'.$p->getEmail();
        }
        return $temp;
    }



    /**
     * @return array|null
     */
    public function getParticipants(): ?array
    {
        return $this->participants;
    }

    /**
     * @param array|null $participants
     */
    public function setParticipants(?array $participants): void
    {
        $this->participants = $participants;
    }




    /**
     * @return array|null
     */
    public function getOrganisateursTab(): ?array
    {
        $temp =[];
        foreach($this->organisateurs as $p){
            $temp[]=$p->getNom().':'.$p->getEmail();
        }
        return $temp;
    }

    /**
     * @return array|null
     */
    public function getOrganisateurs(): ?array
    {
        return $this->organisateurs;
    }

    /**
     * @param array|null $organisateurs
     */
    public function setOrganisateurs(?array $organisateurs): void
    {
        $this->organisateurs = $organisateurs;
    }






    /**
     * @return string
     */
    public function getLieu(): string
    {
        return $this->lieu;
    }

    /**
     * @param string $lieu
     */
    public function setLieu(string $lieu): void
    {
        $this->lieu = $lieu;
    }

    /**
     * @return string
     */
    public function getAdresse(): string
    {
        return $this->adresse;
    }

    /**
     * @param string $adresse
     */
    public function setAdresse(string $adresse): void
    {
        $this->adresse = $adresse;
    }

    /**
     * @return string
     */
    public function getAgenda(): string
    {
        return $this->agenda;
    }

    /**
     * @param string $agenda
     */
    public function setAgenda(string $agenda): void
    {
        $this->agenda = $agenda;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getServeur(): string
    {
        return $this->serveur;
    }

    /**
     * @param string $serveur
     */
    public function setServeur(string $serveur): void
    {
        $this->serveur = $serveur;
    }

    /**
     * @return string
     */
    public function getGroupe(): string
    {
        return $this->groupe;
    }

    /**
     * @param string $groupe
     */
    public function setGroupe(string $groupe): void
    {
        $this->groupe = $groupe;
    }

    /**
     * @return string
     */
    public function getCategories(): ?array
    {
        return $this->categories;
    }

    /**
     * @param string $categories
     */
    public function setCategories(array $categories): void
    {
        $this->categories = $categories;
    }


    /**
     * @return string
     */
    public function getStatut(): string
    {
        return $this->statut;
    }

    /**
     * @return string
     */
    public function getStatutInFrench(): string
    {
        $tab_trad=[
          'COMPLETED' => 'Terminé',
          'IN-PROCESS' => 'En cours',
        ];
        return $tab_trad[$this->statut] ?? $this->statut;
    }


    /**
     * @param string $statut
     */
    public function setStatut(string $statut): void
    {
        $this->statut = $statut;
    }

    /**
     * @return string
     */
    public function getCouleur(): string
    {
        return $this->couleur;
    }

    /**
     * @param string $couleur
     */
    public function setCouleur(string $couleur): void
    {
        $this->couleur = $couleur;
    }


    public function prioriteInFrench(): string
    {

        $tab_trad=[
            '0' => '??',
            '1' => 'Extrement urgent',
            '2' => 'Trés urgent',
            '3' => 'Urgent',
            '4' => 'Priorité élevé',
            '5' => 'moyenne +',
            '6' => 'moyenne',
            '7' => 'moyenne -',
            '8' => 'faible',
            '9' => 'Peut attendre',
        ];
        return $tab_trad[$this->priorite] ?? $this->priorite;
    }


    public function getPriorite(): string
    {
        return $this->priorite;
    }

    public function setPriorite(string $priorite): void
    {
        $this->priorite = $priorite;
    }



    public function getAvancement(): string
    {
        return $this->avancement;
    }

    public function setAvancement(string $avancement): void
    {
        $this->avancement = $avancement;
    }

    public function isFini(): bool
    {
        return $this->fini;
    }



    public function setFini(bool $fini): void
    {
        $this->fini = $fini;
    }




}

templates/agenda/badge_personne.html.twig
<span class="badge-personne" title=" {{ p.nom }} {% if p.email is not empty %}- {{ p.email|trafiquer }}{% endif %}">
    <img src="{{ avatar(p.cle, '', 20) }}" alt="{{ p.nom }}" />
    <span class="nom">{{ p.nom }}</span>
    <span class="caracteristiques">
          {% if cc[p.cle] is defined and cc[p.cle] is not empty  %}
              {% for id_caract in cc[p.cle] %}
                  {% set caract = tab('caracteristique.'~id_caract) %}
                  <span title="{{ caract.nom }} - {{ caract.descriptif }}">{{ caract.symbole }} </span>
              {% endfor %}
          {% endif %}
    </span>
</span>

templates/agenda/evt_card.html.twig
{% set evt = gevt['evts']|first   %}
{% set id_card = 'cal'~evt.id   %}
{% set est_un_groupe = gevt['evts']|length > 1   %}
<div class="card filtre_ob mb-5" id="{{ id_card }}" data-filtre-valeur-cat="{{ evt.categories|join('|') }}" data-filtre-valeur-lieu="{{ evt.lieu }}">
    <div class="card-header" {% if evt.couleur is not empty %} style="border-bottom-color: {{ evt.couleur }};border-bottom-width:3px;"{% endif %}>
        {% if is_granted('ROLE_ADMIN') %}
        <div class="evt_admin">
            <div class="serveur_calendrier">
                <small>Serveur </small>
                <span class="serveur">{{ evt.serveur }}</span>
                <small>Calendrier </small>
                <span class="calendrier" >{{ evt.agenda }}</span>
            </div>
        </div>
        {% endif %}
        <div class="float-end d-flex flex-column">
            <div class="categorie d-inline-flex">
                {% if evt.categories is not empty  %}
                <small>Catégorie </small>

                    <ul class="categorie list-inline">
                        {% for cat in evt.categories  %}
                            <li class="list-inline-item badge text-bg-info">{{ cat }} </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>

        <h4 class="card-title">
            {% if evt.statut=='CANCELLED'  %}
                <span class="badge bg-danger">Annulé</span>
            {% endif %}
            <div class="d-inline-flex">
            {% if est_un_groupe  %}
                <div class="titre_horaire">
                {{ gevt.titre }}
                <h6 class="card-subtitle mt-2 mb-2 text-muted">
                    <i class="fa fa-clock"></i>
                    De {{ gevt.dateDebut|format_datetime('none', 'short',  locale='fr') }} à
                    {{ gevt.dateFin|format_datetime('none', 'short',  locale='fr') }}
                </h6>
                </div>
            {% else %}
                <div class="titre_horaire">
                {{ evt.titre }}
                <h6 class="card-subtitle mt-2 mb-2 text-muted">
                    <i class="fa fa-clock"></i>
                    De {{ evt.dateDebut|format_datetime('none', 'short',  locale='fr') }} à
                    {{ evt.dateFin|format_datetime('none', 'short',  locale='fr') }}
                </h6>
                </div>
            {% endif %}

            </div>
            <div class="btnl btn-lien" role="group" aria-label="button group">
                {% if conf('affichage.boutons_liens') %}
                <div class="btn btn-sm btn-outline-primary"
                     data-clipboard-text="{{ absolute_url(path('agenda')) }}#{{ id_card }}"
                >
                    <i class="fa fa-link"></i>
                </div>
                <div class="btn btn-sm btn-outline-secondary"
                     data-clipboard-text="{{ absolute_url(path('cuisson',{'nom':'@nom@','email':'@email@','ancre':id_card})) }}#{{ id_card }}"
                >
                    <i class="fa fa-link"></i>NL
                </div>
                {% endif %}
                {% if not est_un_groupe and is_granted('ROLE_ADMIN') %}
                <a class="btn btn-sm btn-warning modal-form " href="{{ path('agenda_edit_evt',{'id':evt.id}) }}" >
                    <i class="fa fa-pencil-alt"></i>
                </a>
                <a class="btn btn-sm btn-danger"  data-confirm-supprimer="Confirmez vous la suppression de cet évenement ?"
                   data-href="{{ path('agenda_delete_evt',{'id':evt.id}) }}" >
                    <i class="fa fa-trash-alt"></i>
                </a>
                {% endif %}
            </div>
        </h4>
        </div> <!-- .card-header  -->

        <div class="card-body">
            {% if consultation and evt.presentation is defined and (not evt.presentation=='')  %}
                <p class="card-text">{{ evt.presentation|replace({"\n\n":'<br/>',"\n":'<br/>','\\n\\n':'<br/>','\\n':'<br/>'})|urlify|raw  }}</p>
            {% endif %}
        {% if not consultation and evt.descriptif is defined and (not evt.descriptif=='')  %}

        <p class="card-text">{{ evt.descriptif|replace({"\n\n":'<br/>',"\n":'<br/>','\\n\\n':'<br/>','\\n':'<br/>'})|urlify|raw  }}</p>
        {% endif %}
            {% if evt.nbPersonne and  not consultation  %}
            <p class="nb_personne_souhait"> {{ evt.nbPersonne }} participant·e{% if evt.nbPersonne > 1 %}·s{% endif %} souhaité·e{% if evt.nbPersonne > 1 %}·s{% endif %}</p>
            {% endif %}
        {% if (not evt.lieu=='') or  (not evt.adresse=='')  %}
            <p class="lieu"><i class="fa fa-map-marker" title="Lieu"></i> {{ evt.lieu?? '??'  }} {{ evt.adresse ? ' - '~evt.adresse:''  }} </p>
        {% endif %}



            {% if evt.organisateurs is not empty  %}
                <div class="organisateurs">Organisateurs :
                    <ul class="list-inline">
                        {% for p in evt.organisateurs %}
                            {% include ('agenda/badge_personne.html.twig')  with { "p":p, 'cc':cc} only  %}<br/>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            {% if not est_un_groupe  %}
                {% if not consultation%}
                {% include ('agenda/evt_participant.html.twig')  with { "evt":evt,'class':'','cc':cc} only   %}
                {% endif %}
            {% else %}
            <div class="row evts_creneau">
                {% for ge in gevt['evts'] %}
                    <div class="col-md-6 col-xl-4">
                        <div class="evt_creneau">
                            <div class="btnl btn-lien" role="group" aria-label="button group">
                                {% if is_granted('ROLE_ADMIN') %}
                                    <a class="btn btn-sm btn-warning modal-form " href="{{ path('agenda_edit_evt',{'id':ge.id}) }}" >
                                        <i class="fa fa-pencil-alt"></i>
                                    </a>
                                    <a class="btn btn-sm btn-danger"  data-confirm-supprimer="Confirmez vous la suppression de cet évenement ?"
                                       data-href="{{ path('agenda_delete_evt',{'id':ge.id}) }}" data-token="" >
                                        <i class="fa fa-trash-alt"></i>
                                    </a>
                                {% endif %}
                            </div>
                            <div class="box boite-ge">
                                <div class="box-body">
                                    <div class="texte">
                                        <h6 class="card-subtitle mb-2 text-muted">
                                            <i class="fa fa-clock"></i>
                                            De {{ ge.dateDebut|format_datetime('none', 'short',  locale='fr') }} à
                                            {{ ge.dateFin|format_datetime('none', 'short',  locale='fr') }}
                                        </h6>
                                        <h5>{{ ge.titre[(gevt.titre|length+2):]|trim }}</h5>
                                    </div>
                                    {% if not consultation%}
                                        {% include ('agenda/evt_participant.html.twig')  with { "evt":ge}   %}

                                    {% endif %}
                                    {% if not (tab_calendrier[evt.serveur][evt.agenda]['show_only']??false) %}
                                        {% include ('agenda/bt_participation.twig') with { "evt":ge} %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    {% if  not consultation  %}
    {% include ('agenda/bloc_commentaire.html.twig')  %}
    {% endif  %}
    {% if not est_un_groupe and not consultation and not (tab_calendrier[evt.serveur][evt.agenda]['show_only']??false) %}
        {% include ('agenda/bt_participation.twig')  %}
    {% else %}
    {% endif %}
</div>

templates/agenda/evt_line.html.twig
{% set evt = gevt['evts']|first   %}{% set id_card = 'cal'~evt.id   %}{% set est_un_groupe = gevt['evts']|length > 1   %}
{% if est_un_groupe  %} <div class="date"><i class="fa fa-calendar"></i> {{ gevt.dateDebut|format_datetime('full', 'none',  locale='fr') }}</div>
<div class="titre">{{ gevt.titre }}</div>
{% else %}
<div class="date"><i class="fa fa-calendar"></i> {{ evt.dateDebut|format_datetime(pattern="cccc d MMMM à H:mm",locale='fr') }}</div>
<div class="titre">{{ evt.titre }}</div>
{% endif %}
{% if evt.statut=='CANCELLED'  %}<span class="badge bg-danger">Annulé</span>{% endif %}
{% if evt.descriptif|trim is not empty %}<div class="descriptif">{{ evt.descriptif }}</div>{% endif %}
{% if evt.lieu|trim is not empty %}<div class="lieu">{{ evt.lieu }}</div>{% endif %}
<hr />

templates/agenda/evt_line_spip.html.twig
{% set evt = gevt['evts']|first   %}{% set id_card = 'cal'~evt.id   %}{% set est_un_groupe = gevt['evts']|length > 1   %}
{% if est_un_groupe  %}<glinglin_date|texte={{ evt.dateDebut|format_datetime(pattern="cccc d MMMM à H:mm",locale='fr') }}>

{% if evt.statut=='CANCELLED'  %}<glinglin_alerte|message=Annulé>{% endif %}{{'{{{'~gevt.titre~'}}}'}}
{% else %}
<glinglin_date|texte={{ evt.dateDebut|format_datetime(pattern="cccc d MMMM à H:mm",locale='fr') }}>{% if evt.lieu|trim is not empty %}<glinglin_lieu|texte={{ evt.lieu }}>{% endif %}

{% if evt.statut=='CANCELLED'  %}<glinglin_alerte|texte=Annulé>{% endif %}{{ '{{{'~evt.titre~'}}}' }}
{% endif %}
{% if evt.descriptif|trim is not empty %}{{ evt.descriptif }}{% endif %}

----

templates/agenda/evt_tr.html.twig
{% set evt = gevt['evts']|first   %}
{% set id_card = 'cal'~evt.id   %}
{% set est_un_groupe = gevt['evts']|length > 1   %}
<div class="filtre_ob mb-5" id="{{ id_card }}" data-filtre-valeur-cat="{{ evt.categories|join('|') }}" data-filtre-valeur-lieu="{{ evt.lieu|join('|') }}">

<div class="ligne_tr"{% if evt.couleur is not empty %} style="border-left-color: {{ evt.couleur }};border-left-width:3px;"{% endif %}>
<div class="row">

    {% if is_granted('ROLE_ADMIN') %}
        <div class="evt_admin col-md-12">
            <div class="serveur_calendrier">
                <small>Serveur </small>
                <span class="serveur">{{ evt.serveur }}</span>
                <small>Calendrier </small>
                <span class="calendrier" >{{ evt.agenda }}</span>
            </div>
        </div>
    {% endif %}
        {% if est_un_groupe  %}
        <div class="titre col-md-12">
                <div class="d-inline-flex">
                    {{ gevt.titre }}
                </div>
            <div class="lieu">
                {% if (not evt.lieu=='') or  (not evt.adresse=='')  %}
                    <p>Lieu : {{ evt.lieu?? '??'  }} {{ evt.adresse ? ' - '~evt.adresse:''  }} </p>
                {% endif %}
            </div>
        </div>

        {% for ge in gevt['evts'] %}
            <div class="evt_creneau">
                <div class="row">
                    <div class="col-lg-8">
                        <span class="horaire text-muted">
                        <i class="fa fa-clock"></i>
                        De {{ ge.dateDebut|format_datetime('none', 'short',  locale='fr') }} à
                        {{ ge.dateFin|format_datetime('none', 'short',  locale='fr') }}
                        </span>
                        <div class="titre">{{ ge.titre[(gevt.titre|length+2):]|trim }}</div>
                    </div>
                    <div class="col-lg-4">
                        {% include ('agenda/evt_nb_participant.html.twig')  with { "evt":ge}   %}
                        {% if not consultation and not (tab_calendrier[evt.serveur][evt.agenda]['show_only']??false) %}
                            {% include ('agenda/bt_participation.twig') with { "evt":ge} %}
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}

        {% else %}
    <div class="col-lg-8">
        {% if evt.statut=='CANCELLED'  %}
            <span class="badge bg-danger">Annulé</span>
        {% endif %}



                <div class="titre_horaire">


                        <div class="titre">{{ evt.titre }}</div>
                        <span class="horaire text-muted">
                        <i class="fa fa-clock"></i>
                        De {{ evt.dateDebut|format_datetime('none', 'short',  locale='fr') }} à
                             {{ evt.dateFin|format_datetime('none', 'short',  locale='fr') }}
                         </span>

                </div>

            {% if (not evt.lieu=='') or  (not evt.adresse=='')  %}
                <p>Lieu : {{ evt.lieu?? '??'  }} {{ evt.adresse ? ' - '~evt.adresse:''  }} </p>
            {% endif %}
        </div>
        <div class="col-lg-4">
            {% if not consultation%}
            {% include ('agenda/evt_nb_participant.html.twig')  with { "evt":evt,'class':''} only   %}
            {% endif %}
            {% set identite = identite() %}
            {% if not est_un_groupe    %}
                {% if  not (tab_calendrier[evt.serveur][evt.agenda]['show_only']??false) %}
                {% include ('agenda/bt_participation.twig')%}
                {% endif %}
            {% else %}

                    {% for ge in gevt['evts'] %}
                    <div class="evt_creneau">
                        <div class="row">
                            <div class="col-lg-6 col-xl-4">

                                <div class="texte">
                                    <h6 class="mb-2 text-muted">
                                        <i class="fa fa-clock"></i>
                                        De {{ ge.dateDebut|format_datetime('none', 'short',  locale='fr') }} à
                                        {{ ge.dateFin|format_datetime('none', 'short',  locale='fr') }}
                                    </h6>
                                    <h5> {% if ge.statut=='CANCELLED'  %}
                                            <span class="badge bg-danger">Annulé</span>
                                        {% endif %}
                                        {{ ge.titre[(gevt.titre|length+2):]|trim }}</h5>
                                </div>
                                {% if not consultation%}
                                    {% include ('agenda/evt_participant.html.twig')  with { "evt":ge}   %}
                                {% endif %}
                                {% if  not (tab_calendrier[evt.serveur][evt.agenda]['show_only']??false) %}
                                    {% include ('agenda/bt_participation.twig') with { "evt":ge} %}
                                {% endif %}

                            </div>
                        </div>
                    </div>
                    {% endfor %}

            {% endif %}
        </div>
 {% endif %}

</div>
</div>
</div>

templates/agenda/index.html.twig
{% extends 'base.html.twig' %}
{% block menu %}
    {% if not consultation %}
    {% set identite = identite() %}
<div  id="identite">
    {% if not identite.ok %}
        <a  class="btn btn-outline-primary m-1 btn-modal"  data-selecteur="form_ident" data-title="Qui es tu ?"><i class="fa fa-user"></i> Qui es tu ?</a>
        <div class="row d-none" id="identite_form">
            <div class="col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">
                {% include('inclure/identite.html.twig') %}
            </div>
        </div>
    {% else %}
        {% include('inclure/identite.html.twig') %}
    {% endif %}
</div>
    {% endif %}
    {{ parent() }}
    <div class="d-none" id="menu-affichage">
        <div class="d-grid gap-2">
            {% set route=(consultation)?'agenda_public':'agenda' %}
            <a href="{{ path(route,{'mode_affichage':'calendrier'}) }}" class="btn btn-outline-primary d-none d-lg-block"  ><i class="fa fa-calendar"></i> Calendrier</a>
            <a href="{{ path(route,{'mode_affichage':'liste'}) }}" class="btn btn-outline-primary" ><i class="fa fa-list"></i> Liste étendue</a>
            <a href="{{ path(route,{'mode_affichage':'liste_compacte'}) }}" class="btn btn-outline-primary">  <i class="fa fa-list"></i> Liste compacte </a>
        </div>
    </div>
{% endblock %}

{% block menu_btn %}
    {% if config_affichage.minicalendrier and mode_affichage != 'calendrier' %}
    <a id="btn_minicalendrier" class="btn btn-outline-secondary  btn-modal"  data-selecteur="minicalendriers" data-title="<i class='fa fa-calendar'></i> Calendriers"><i class="fa fa-calendar"></i></a>
    {% endif %}
    {% if config_affichage.filtre %}
    <a id="btn_filter" class="btn btn-outline-secondary btn-modal" data-selecteur="barre_filtre" data-title="<i class='fa fa-filter'></i> Filtres"><i class="fa fa-filter"></i></a>
    {% endif %}
    <a class="btn btn-outline-secondary btn-modal" data-selecteur="menu-affichage" title="Mode d'affichage"><i class="fa fa-paint-brush"></i> </a>
    {% if is_granted('ROLE_ADMIN') %}
        <a href="{{ path('evenement') }}" class="btn btn-outline-secondary" title="Ajouter des evts"><i class="fa fa-plus"></i></a>
    {% endif %}
{% endblock %}

{% block entete %}
{{ parent() }}

  <div class="row" >
      <div class="col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">
          <div id="alerte_rafraichir" class="alert alert-warning sticky-top">
              L'agenda a été modifié ou complété, Souhaitez-vous rafraîchir la page ? <a href="{{ path('agenda') }}" class="btn btn-primary">Rafraichir</a>
          </div>
      </div>
  </div>
{% endblock %}


{% block content %}
    {% include ('agenda/filtres.html.twig')  with { "evts":evts}   %}
    <div  id="minicalendriers" class="d-none" >
        <div class="row">
            <div class="col-lg-6 ">
                {% include ('agenda/mini_calendrier.html.twig')  with { "mois":tab_mois['courant']}   %}
            </div>
            <div class="col-lg-6  ">
                {% include ('agenda/mini_calendrier.html.twig')  with { "mois":tab_mois['suivant']}   %}
            </div>
        </div>
    </div>
    {% if mode_affichage == 'calendrier'  %}
        <div class="box" id="evts">
            <div class="box-body">
                <div id="calendar"
                    data-filtres="{{ tab_filtres|json_encode  }}"
                    data-consultation="{{ consultation?1:0  }}"
                >
                </div>
            </div>
        </div>
    {% else %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-10 offset-lg-1 col-xl-8 offset-xl-2">

                <div id="evts" data-refresh="{{ time }}">
                {% set date_temp = '' %}
               {% for date,gevt in evts %}
                   {% set date_jour = gevt.dateDebut|format_datetime('full', 'none',  locale='fr') %}
                   {% if date_temp != date_jour %}
                        {% if not loop.first %}</div>{% endif %}
                        <h3 class="cat_filtre mt-2 mb-3" id="date_{{ gevt.dateDebut|date('Ymd') }}"><i class="fa fa-calendar"></i> {{ date_jour|capitalize }} <i class="fa fa-calendar"></i></h3>
                        <div class="evt_date">
                   {% else %}
                   {% endif %}
                            {% if mode_affichage=="liste_compacte"  %}
                            {% include ('agenda/evt_tr.html.twig')  with { "gevt":gevt}   %}
                            {% else %}
                            {% include ('agenda/evt_card.html.twig')  with { "gevt":gevt}   %}
                            {% endif %}
                   {% if date_temp != date_jour %}
                   {% endif %}
                    {% set date_temp=date_jour %}
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}